"""add_stats_fields

Revision ID: 26fe05d99c29
Revises: cdf7c4134f2b
Create Date: 2025-11-27 21:55:26.360799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26fe05d99c29'
down_revision: Union[str, Sequence[str], None] = 'cdf7c4134f2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_attempts', sa.Column('duration_seconds', sa.Integer(), nullable=True))
    op.add_column('question_attempts', sa.Column('status', sa.String(), nullable=False, server_default='attempted'))
    op.add_column('user_taxonomy_stats', sa.Column('questions_viewed', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('user_taxonomy_stats', sa.Column('total_time_seconds', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_taxonomy_stats', 'total_time_seconds')
    op.drop_column('user_taxonomy_stats', 'questions_viewed')
    op.drop_column('question_attempts', 'status')
    op.drop_column('question_attempts', 'duration_seconds')
    # ### end Alembic commands ###
