"""add_google_id_to_users

Revision ID: cdf7c4134f2b
Revises: e32ab8063a90
Create Date: 2025-11-25 17:54:25.824972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdf7c4134f2b'
down_revision: Union[str, Sequence[str], None] = 'e32ab8063a90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quiz_attempts', 'quiz_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_quiz_attempts_quiz_version_id'), 'quiz_attempts', ['quiz_version_id'], unique=False)
    op.add_column('users', sa.Column('google_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profile_picture_url', sa.Text(), nullable=True))
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_column('users', 'profile_picture_url')
    op.drop_column('users', 'google_id')
    op.drop_index(op.f('ix_quiz_attempts_quiz_version_id'), table_name='quiz_attempts')
    op.alter_column('quiz_attempts', 'quiz_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
